export const styles = {
  page: {
    fontFamily:
      'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    padding: "clamp(12px, 2vw, 18px) clamp(12px, 2vw, 16px) clamp(24px, 3vw, 28px)",
    maxWidth: "1280px",
    margin: "0 auto",
    color: "#e5e7eb",
    width: "100%",
    minWidth: 0,
    overflowX: "clip",
  } as const,
  header: {
    marginBottom: "0",
    textAlign: "left",
    minWidth: 0,
  } as const,
  title: {
    fontSize: "clamp(28px, 4.2vw, 42px)",
    fontWeight: 800,
    lineHeight: 1.08,
    letterSpacing: "-0.03em",
    margin: 0,
  } as const,
  subtitle: {
    fontSize: "clamp(14px, 1.7vw, 15px)",
    color: "#b8c1cc",
    margin: 0,
    maxWidth: "760px",
  } as const,
  button: {
    width: "100%",
    minHeight: "52px",
    padding: "12px 16px",
    borderRadius: "12px",
    border: "1px solid #334155",
    background: "#0f172a",
    color: "#f8fafc",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontWeight: 600,
    minWidth: 0,
  } as const,
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(320px, 100%), 1fr))",
    gap: "18px",
  } as const,
  card: {
    background: "#111827",
    border: "1px solid #243041",
    borderRadius: "16px",
    padding: "clamp(14px, 2vw, 18px)",
    minWidth: 0,
    overflowX: "clip",
  } as const,
  sectionTitle: {
    fontSize: "clamp(20px, 3vw, 24px)",
    fontWeight: 800,
    lineHeight: 1.15,
    margin: 0,
  } as const,
  list: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  } as const,
  listItem: {
    padding: "10px 0",
    borderBottom: "1px solid #1f2937",
  } as const,
  sourceList: {
    listStyle: "none",
    paddingLeft: "12px",
    marginTop: "8px",
    marginBottom: 0,
  } as const,
  sourceItem: {
    fontSize: "14px",
    color: "#cbd5e1",
    padding: "2px 0",
  } as const,
  error: {
    color: "#fecdd3",
    marginTop: "12px",
  } as const,
  success: {
    color: "#bbf7d0",
    marginTop: "12px",
  } as const,
  warning: {
    color: "#fbbf24",
    marginTop: "8px",
  } as const,
  info: {
    color: "#93c5fd",
    marginTop: "8px",
  } as const,
  empty: {
    color: "#94a3b8",
  } as const,
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  } as const,
  input: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid #334155",
    background: "#0b1220",
    color: "#f8fafc",
    minWidth: 0,
  } as const,
  select: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid #334155",
    background: "#0b1220",
    color: "#f8fafc",
    minWidth: 0,
  } as const,
  textarea: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid #334155",
    background: "#0b1220",
    color: "#f8fafc",
    minHeight: "90px",
    resize: "vertical",
    minWidth: 0,
  } as const,
  formTitle: {
    fontSize: "clamp(18px, 2.5vw, 20px)",
    fontWeight: 800,
    marginBottom: "12px",
  } as const,
  formLabel: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#cbd5e1",
  } as const,

  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginBottom: "0",
  } as const,
  statCard: {
    background: "#111827",
    border: "1px solid #243041",
    borderRadius: "16px",
    padding: "18px",
    textAlign: "center",
    minWidth: 0,
  } as const,
  statValue: {
    fontSize: "clamp(24px, 3.2vw, 30px)",
    fontWeight: 800,
    marginBottom: "6px",
  } as const,
  statLabel: {
    fontSize: "14px",
    color: "#b8c1cc",
  } as const,

  actionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  } as const,
  actionCard: {
    background: "#111827",
    border: "1px solid #243041",
    borderRadius: "16px",
    padding: "18px",
    textAlign: "left",
    cursor: "pointer",
    minWidth: 0,
  } as const,
  actionTitle: {
    fontSize: "clamp(18px, 2.6vw, 20px)",
    fontWeight: 800,
    marginBottom: "8px",
  } as const,
  actionText: {
    color: "#cbd5e1",
    fontSize: "14px",
    lineHeight: 1.5,
  } as const,

  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(2, 6, 23, 0.76)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",
    zIndex: 1000,
  } as const,
  modal: {
    width: "100%",
    maxWidth: "1080px",
    maxHeight: "92vh",
    overflowY: "auto",
    background: "#0b1220",
    border: "1px solid #243041",
    borderRadius: "20px",
    padding: "0",
    minWidth: 0,
    overflowX: "clip",
  } as const,
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    marginBottom: "0",
    minWidth: 0,
  } as const,
  modalTitle: {
    fontSize: "clamp(22px, 3vw, 28px)",
    fontWeight: 800,
    margin: 0,
  } as const,
  closeButton: {
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #334155",
    background: "#111827",
    color: "#f8fafc",
    cursor: "pointer",
  } as const,
};
