export const styles = {
  page: {
    fontFamily:
      'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    padding: "18px 14px 28px",
    maxWidth: "1240px",
    margin: "0 auto",
    color: "var(--nf-text)",
  } as const,
  header: {
    marginBottom: "0",
    textAlign: "left",
  } as const,
  title: {
    fontSize: "clamp(30px, 4.8vw, 44px)",
    fontWeight: 800,
    lineHeight: 1.08,
    letterSpacing: "-0.03em",
    margin: 0,
    color: "var(--nf-text-strong)",
  } as const,
  subtitle: {
    fontSize: "15px",
    color: "var(--nf-text-muted)",
    margin: 0,
    maxWidth: "760px",
  } as const,
  button: {
    width: "100%",
    minHeight: "56px",
    padding: "12px 16px",
    borderRadius: "12px",
    border: "1px solid var(--nf-border-strong)",
    background: "var(--nf-button-bg)",
    color: "var(--nf-button-text)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontWeight: 600,
  } as const,
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "18px",
  } as const,
  card: {
    background: "var(--nf-card-bg)",
    border: "1px solid var(--nf-border)",
    borderRadius: "16px",
    padding: "18px",
  } as const,
  sectionTitle: {
    fontSize: "24px",
    fontWeight: 800,
    lineHeight: 1.15,
    margin: 0,
    color: "var(--nf-text-strong)",
  } as const,
  list: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  } as const,
  listItem: {
    padding: "10px 0",
    borderBottom: "1px solid var(--nf-border)",
  } as const,
  sourceList: {
    listStyle: "none",
    paddingLeft: "12px",
    marginTop: "8px",
    marginBottom: 0,
  } as const,
  sourceItem: {
    fontSize: "14px",
    color: "var(--nf-text)",
    padding: "2px 0",
  } as const,
  error: {
    color: "var(--nf-error-text)",
    marginTop: "12px",
  } as const,
  success: {
    color: "var(--nf-success-text)",
    marginTop: "12px",
  } as const,
  warning: {
    color: "var(--nf-warning-text)",
    marginTop: "8px",
  } as const,
  info: {
    color: "var(--nf-info-text)",
    marginTop: "8px",
  } as const,
  empty: {
    color: "var(--nf-text-soft)",
  } as const,
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  } as const,
  input: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid var(--nf-border-strong)",
    background: "var(--nf-input-bg)",
    color: "var(--nf-text-strong)",
  } as const,
  select: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid var(--nf-border-strong)",
    background: "var(--nf-input-bg)",
    color: "var(--nf-text-strong)",
  } as const,
  textarea: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid var(--nf-border-strong)",
    background: "var(--nf-input-bg)",
    color: "var(--nf-text-strong)",
    minHeight: "90px",
    resize: "vertical",
  } as const,
  formTitle: {
    fontSize: "20px",
    fontWeight: 800,
    marginBottom: "12px",
    color: "var(--nf-text-strong)",
  } as const,
  formLabel: {
    fontSize: "13px",
    fontWeight: 600,
    color: "var(--nf-text)",
  } as const,
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginBottom: "0",
  } as const,
  statCard: {
    background: "var(--nf-card-bg)",
    border: "1px solid var(--nf-border)",
    borderRadius: "16px",
    padding: "18px",
    textAlign: "center",
  } as const,
  statValue: {
    fontSize: "30px",
    fontWeight: 800,
    marginBottom: "6px",
    color: "var(--nf-text-strong)",
  } as const,
  statLabel: {
    fontSize: "14px",
    color: "var(--nf-text-muted)",
  } as const,
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  } as const,
  actionCard: {
    background: "var(--nf-card-bg)",
    border: "1px solid var(--nf-border)",
    borderRadius: "16px",
    padding: "18px",
    textAlign: "left",
    cursor: "pointer",
  } as const,
  actionTitle: {
    fontSize: "20px",
    fontWeight: 800,
    marginBottom: "8px",
    color: "var(--nf-text-strong)",
  } as const,
  actionText: {
    color: "var(--nf-text)",
    fontSize: "14px",
    lineHeight: 1.5,
  } as const,
  overlay: {
    position: "fixed",
    inset: 0,
    background: "var(--nf-overlay-bg)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",
    zIndex: 1000,
  } as const,
  modal: {
    width: "100%",
    maxWidth: "1080px",
    maxHeight: "min(92vh, calc(100dvh - 24px))",
    overflow: "hidden",
    background: "var(--nf-modal-bg)",
    border: "1px solid var(--nf-border)",
    borderRadius: "20px",
    padding: "0",
    display: "flex",
    flexDirection: "column",
  } as const,
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    marginBottom: "0",
  } as const,
  modalTitle: {
    fontSize: "28px",
    fontWeight: 800,
    margin: 0,
    color: "var(--nf-text-strong)",
  } as const,
  closeButton: {
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid var(--nf-border-strong)",
    background: "var(--nf-button-bg)",
    color: "var(--nf-button-text)",
    cursor: "pointer",
  } as const,
};
